---
# tasks file for create_cert
- name: Generate certs
  command: openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 365 -out domain.crt -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_locality}}/O={{ cert_org }}/OU={{ cert_org_unit }}/CN={{ mirror_reg_fqdn }}/emailAddress={{ cert_email }}"
  args:
    chdir: "/etc/pki/ca-trust/source/anchors/"

- name: Update ca trust
  command: update-ca-trust

- name: Fetch the key from web server
  fetch:
    src: /etc/pki/ca-trust/source/anchors/domain.key
    dest: /etc/pki/ca-trust/source/anchors/domain.key
    flat: yes

- name: Fetch the cert from the web server
  fetch:
    src: /etc/pki/ca-trust/source/anchors/domain.crt
    dest: /etc/pki/ca-trust/source/anchors/domain.crt
    flat: yes
