---
- name: Test
  hosts: mirror
  serial: 1

  tasks:

  - name: test1
    debug:
      msg:  test "{{ inventory_hostname }}"

  - name: test2
    debug:
      msg: test2 "{{ inventory_hostname }}"

#  - name: test
#    debug:
#      msg: "{{ hostvars[item]['rhel7_dest'] }}"
#    when:
#    - inventory_hostname == 'mirror.ocp.example.com'
#    - "'mirror' in hostvars[item]['group_names']"
#    loop: "{{ groups['all'] }}"

