---
- name: Test
  hosts: localhost

  tasks:
  - name: test
    debug:
      msg: "{{ hostvars[item] }}"
    when: "'bootstrap' in hostvars[item]['group_names'] or 'masters' in hostvars[item]['group_names']"
    loop: "{{ groups['all'] }}"
