---
- name: Provision Vsphere VM
  hosts: preflight

  roles:
#     - infra_setup


  tasks:

- name: Provision Vsphere VM
  hosts: localhost

  roles:
#    - vmware_provision
    - custom_iso

  tasks:

