---
#- name: Provision Vsphere VM
#  hosts: preflight
#
#  roles:
#    - infra_setup


- name: Health Check
  hosts: mirror

  roles:
    - firewalld_open
    - apache_install
    - create_html

  tasks:

- name: DNS LB Check
  hosts: mirror
  serial: 1
  
  roles:
    - dns_lb_check

  pre_tasks:
  - name: Ensure file is absent
    file:
      path: /tmp/curl_test.txt
      state: absent
    delegate_to: 127.0.0.1


#- name: Provision Vsphere VM
#  hosts: localhost
#  gather_facts: no

#  roles:
#    - vmware_provision
#    - custom_iso

#  tasks:

