---
# tasks file for dns_lb_check
- name: Set the state of a virtual machine to poweron
  vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "/{{ vm_datacenter }}/{{ cluster_id }}{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: powered-on
  delegate_to: localhost
  register: status

- name: output power status
  debug:
    msg: "{{ status }}"

- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
    timeout: 300
