---
# tasks file for vmware_provision
- name: Debug
  debug:
    msg: "{{ vcenter_hostname, vcenter_username, vcenter_password, vm_folder, hostvars[item]['vm_name'], vm_state, vm_state, vm_datacenter, vm_guest_id, vm_template, hostvars[item]['vm_disk_size'], vm_datastore, hostvars[item]['vm_memory'], hostvars[item]['vm_cpu'], vm_network_name, hostvars[item]['vm_ip'], vm_netmask, vm_gateway, vm_domain, hostvars[item]['vm_hostname'], vm_dns1, vm_dns2 }}"
  loop: "{{ groups['all'] }}"

- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vm_folder }}"
    name: "{{ hostvars[item]['vm_name'] }}"
    state: "{{ vm_state }}"
    datacenter: "{{ vm_datacenter }}"
    guest_id: "{{ vm_guest_id }}"
    template: "{{ vm_template }}"
    disk:
    - size_gb: "{{ hostvars[item]['vm_disk_size'] }}"
      type: thin
      datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ hostvars[item]['vm_memory'] }}"
      num_cpus: "{{ hostvars[item]['vm_cpu'] }}"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
    networks:
    - name: "{{ vm_network_name }}"
      ip: "{{ hostvars[item]['vm_ip'] }}"
      netmask: "{{ vm_netmask }}"
      gateway: "{{ vm_gateway }}"
    customization:
      domain: "{{ vm_domain }}"
      hostname: "{{ hostvars[item]['vm_hostname'] }}"
      dns_servers:
      - "{{ vm_dns1 }}"
      - "{{ vm_dns2 }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
  loop: "{{ groups['all'] }}"

- name: Wait for system to become reachable over SSH
  wait_for_connection:
    timeout: 300
