---
# tasks file for vmware_provision
- name: Create a virtual machine from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: /UOB_OCP
    name: test_vm2
    state: poweredon
    datacenter: ocp
    guest_id: rhel7_64Guest
    template: rhel7.7
    disk:
    - size_gb: 16
      type: thin
      datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: 1000
      num_cpus: 1
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
      # cdrom:
      # type: iso
      # iso_path: "[1T-monster] rhel-server-7.7-x86_64-dvd.iso"
    networks:
    - name: VM Network
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy

- name: Wait for system to become reachable over SSH
  wait_for_connection:
    timeout: 300
