---
# tasks file for apache_install
- name: Install apache
  yum:
    name: httpd
    state: latest


- name: Configure apache config file
  template:
    src: httpd_config.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: '0644'
  notify:
    - restart apache

- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Enable service httpd
  service:
    name: httpd
    enabled: yes
